My Project: Entitee Class Reference
Entitee Class Reference abstract
Classe mère des différentes Entitee.
#include <Entitee.hpp>
Public Member Functions
Entitee (int x, int y)
Constructeur de la classe Entitee.
virtual ~Entitee ()
Destructeur de la classe Entitee.
int getX ()
Récupère la coordonée X de l'Entitee.
int getY ()
Récupère la coordonée Y de l'Entitee.
void setPos (Vector2 pos)
Setter de _pos.
virtual void Afficher ()=0
Affichage de l'Entitee.
virtual EntiteeType JeSuis ()=0
Renvoi la classe de l'Entitee.
Vector2 getVector ()
Récupère le vecteur contenant la position actuel de l'Entitee.
bool isMort ()
Getter de _mort.
void setMort (bool available)
Setter de _mort.
Protected Attributes
Vector2 _pos
Position actuel de l'Entitee.
bool _mort = false
Statut de l'Entitee.
Detailed Description
Classe mère des différentes Entitee.
Constructor & Destructor Documentation
Entitee()
Entitee::Entitee (int x, int y)
Constructeur de la classe Entitee.
Parameters
x position x de l'Entitee
y position y de l'Entitee
Member Function Documentation
getVector()
Vector2 Entitee::getVector ()
Récupère le vecteur contenant la position actuel de l'Entitee.
Returns
Vector2 vecteur
Referenced by Plateau::caseLibre(), Passifish::Tuable(), and Agent::update().
getX()
int Entitee::getX ()
Récupère la coordonée X de l'Entitee.
Returns
int La coordonée X
Referenced by Plateau::Deplacer().
getY()
int Entitee::getY ()
Récupère la coordonée Y de l'Entitee.
Returns
int La coordonée Y
Referenced by Plateau::Deplacer().
isMort()
bool Entitee::isMort ()
Getter de _mort.
Returns
true si l'Entitee est mort
false dans le cas contraire
JeSuis()
virtual EntiteeType Entitee::JeSuis () pure virtual
Renvoi la classe de l'Entitee.
Returns
EntiteeType
Implemented in Agressif, Passifish, and Ressource.
Referenced by Plateau::Delete(), Agent::seReproduire(), Passifish::Traitement(), and Agressif::Traitement().
setMort()
void Entitee::setMort (bool available)
Setter de _mort.
Parameters
available nouvelle valeur de _mort
setPos()
void Entitee::setPos (Vector2 pos)
Setter de _pos.
Parameters
pos nouvelle valeur de _pos
Referenced by Plateau::Deplacer().
The documentation for this class was generated from the following files:
Entitee.hpp
Entitee.cpp