My Project: Plateau Class Reference
Plateau Class Reference
Plateau sur lequel évolue des Agent.
#include <Plateau.hpp>
Public Member Functions
Plateau ()
Constructeur de la classe Plateau. Génération du _plateau aléatoirement.
Plateau (std::string nom)
Constructeur de la classe Plateau à partir d'un fichier.
~Plateau ()
Destructeur de la class Plateau.
void Afficher ()
Affiche le contenu actuel du Plateau.
void Update ()
Réalise une mise à de tous les Agent sur le _plateau.
void Ajouter (Entitee *e, int x, int y)
Ajoute une Entitee sur le _plateau.
void createAgent (EntiteeType type, Vector2 position)
Crée un Agent selon le type passé en paramètres.
void Ajouter (Agent *e, int x, int y)
Ajoute un Agent sur le _plateau.
void Delete (Entitee *e)
Supprime une Entitee du Plateau et la déclare comme morte pour ne pas la traiter dans le Vecteur _agents.
Entitee * recupCase (int x, int y)
Récupère le contenu d'une case du _plateau à une position choisie.
void Deplacer (Entitee *e, Vector2 v)
Déplace une Entitee sur le Plateau.
Vector2 caseLibre (Entitee *e)
Récupère une case libre autour d'une Entitee.
Vector2 PathFinding (Vector2 depart, Vector2 arrive)
Calcul le déplacement à réaliser pour aller d'une position de depart à une position d'arrivée en fonction de l'êtat actuel du plateau.
Vector2 Recup_Chemin (Vector2 depart, Vector2 arrive, std::array< std::array< int, TAILLE_PLATEAU >, TAILLE_PLATEAU > _matrice)
Récupération du déplacement à réaliser grace à la _matrice contenant les chemins possible.
void FreeDead ()
Libère les Agent mort lors de la procédure Update.
void SpawnRessource ()
Crée une ressource sur le _plateau sur une case libre.
Detailed Description
Plateau sur lequel évolue des Agent.
Constructor & Destructor Documentation
Plateau()
Plateau::Plateau (std::string nom)
Constructeur de la classe Plateau à partir d'un fichier.
Parameters
nom du fichier à utiliser
Member Function Documentation
Ajouter() [1/2]
void Plateau::Ajouter (Entitee * e, int x, int y)
Ajoute une Entitee sur le _plateau.
Parameters
e Entitee à ajouter
x position x de l'Entitee
y position y de l'Entitee
Referenced by SpawnRessource().
Ajouter() [2/2]
void Plateau::Ajouter (Agent * e, int x, int y)
Ajoute un Agent sur le _plateau.
Parameters
e Agent à ajouter
x Position x de l'Agent
y Position y de l'Agent
caseLibre()
Vector2 Plateau::caseLibre (Entitee * e)
Récupère une case libre autour d'une Entitee.
Parameters
e Entitee autour de laquelle faire la recherche
Returns
Vector2 Une case libre autour, (-1, -1) si aucune case n'est trouvée
Referenced by Agent::seReproduire().
createAgent()
void Plateau::createAgent (EntiteeType type, Vector2 position)
Crée un Agent selon le type passé en paramètres.
Parameters
type type de l'Agent à créer
position position à laquel créer l'Agent
Referenced by Plateau().
Delete()
void Plateau::Delete (Entitee * e)
Supprime une Entitee du Plateau et la déclare comme morte pour ne pas la traiter dans le Vecteur _agents.
Parameters
e Entitee à supprimer
Referenced by Agent::manger(), and Update().
Deplacer()
void Plateau::Deplacer (Entitee * e, Vector2 v)
Déplace une Entitee sur le Plateau.
Parameters
e Entitee à déplacer
v Déplacement à éffectuer
Referenced by Agent::move().
PathFinding()
Vector2 Plateau::PathFinding (Vector2 depart, Vector2 arrive)
Calcul le déplacement à réaliser pour aller d'une position de depart à une position d'arrivée en fonction de l'êtat actuel du plateau.
Parameters
depart Vector2 contenant la position de départ
arrive Vector2 contenant la position d'arrivée
Returns
Vector2 Déplacement à éffectuer
Referenced by Agent::update().
Recup_Chemin()
Vector2 Plateau::Recup_Chemin (Vector2 depart, Vector2 arrive, std::array< std::array< int, TAILLE_PLATEAU >, TAILLE_PLATEAU > _matrice)
Récupération du déplacement à réaliser grace à la _matrice contenant les chemins possible.
Parameters
depart Vector2 contenant la position de départ
arrive Vector2 contenant la position de arrivée
_matrice Contient au moins un chemin relliant le position de dépat et celle d'arrivée
Returns
Vector2 Déplacement à effectuer
Referenced by PathFinding().
recupCase()
Entitee * Plateau::recupCase (int x, int y)
Récupère le contenu d'une case du _plateau à une position choisie.
Parameters
x
y
Returns
Entitee* Pointeur sur le contenu de la case
Referenced by Agent::EnVue(), Agent::move(), SpawnRessource(), and Agent::update().
The documentation for this class was generated from the following files:
Plateau.hpp
Plateau.cpp