My Project: Vector2 Class Reference
Vector2 Class Reference
Vecteur à deux dimensions stockant une position x et y.
#include <Vector2.hpp>
Public Member Functions
Vector2 (int x, int y)
Constructeur de la classe Vector2.
Vector2 (Vector2 const &v)
Constructeur par copie de la classe Vector2.
int getX () const
Getter de _x.
int getY () const
Getter de _y.
void setX (int x)
Setter de _x.
void setY (int y)
Setter de _y.
bool isValidPosition ()
Vérifie que les coordonnées du Vector2 sont supérieurs à 0.
int distance (Vector2 v2)
Calcule la distance entre deux Vector2.
Detailed Description
Vecteur à deux dimensions stockant une position x et y.
Constructor & Destructor Documentation
Vector2() [1/2]
Vector2::Vector2 (int x, int y)
Constructeur de la classe Vector2.
Parameters
x position x du Vector2
y position y de Vector2
Vector2() [2/2]
Vector2::Vector2 (Vector2 const & v)
Constructeur par copie de la classe Vector2.
Parameters
v Vector2 à copier
Member Function Documentation
distance()
int Vector2::distance (Vector2 v2)
Calcule la distance entre deux Vector2.
Parameters
v2 Vector2 avec lequelle faire la conparaison
Returns
int distance entre les deux Vector2
Referenced by Passifish::Tuable().
getX()
int Vector2::getX () const
Getter de _x.
Returns
int la valeur de _x
Referenced by Plateau::Deplacer(), distance(), Agent::EnVue(), Entitee::getX(), Agent::move(), operator!=(), operator==(), Plateau::PathFinding(), Plateau::Recup_Chemin(), Entitee::setPos(), and Agent::update().
getY()
int Vector2::getY () const
Getter de _y.
Returns
int la valeur de _y
Referenced by Plateau::Deplacer(), distance(), Agent::EnVue(), Entitee::getY(), Agent::move(), operator!=(), operator==(), Plateau::PathFinding(), Plateau::Recup_Chemin(), Entitee::setPos(), and Agent::update().
isValidPosition()
bool Vector2::isValidPosition ()
Vérifie que les coordonnées du Vector2 sont supérieurs à 0.
Returns
true la position est valide
false la position est invalide
Referenced by Agent::seReproduire().
setX()
void Vector2::setX (int x)
Setter de _x.
Parameters
x nouvelle valeur de x
Referenced by Plateau::PathFinding(), and Entitee::setPos().
setY()
void Vector2::setY (int y)
Setter de _y.
Parameters
y nouvelle valeur de y
Referenced by Plateau::PathFinding(), and Entitee::setPos().
The documentation for this class was generated from the following files:
Vector2.hpp
Vector2.cpp